### ISSUE TITLE
Is this backend provides hardware acceleration?

### ISSUE THREAD

**Issue by dossalab** [Igalia/WPEBackend-fdo#113]
I'm sorry if this issue is unrelated to this backend - I poorly understand WPE architecture or browser architecture in general...

I built an image with mainline buildroot with linux 5.4, mesa (kmsro + lima), weston, glmark, cog, wpewebkit and fdo backend.
The weston and glmark works just fine with decent fps and effects. WebKit launches fine too, but I am unable to run any webgl demo (there is just black screen). [Canvas test](https://www.smashcat.org/av/canvas_test/) works with 11-17 fps.
So I think I am not getting hardware acceleration, but I don't know where is the issue. I've tried to patch cairo to support EGL, tweak some options in package's mk file (-DENABLE_GLES2=ON, -DENABLE_ACCELERATED_2D_CANVAS=ON) but there is no difference.
I would probably build wpe from Igalia's forked buildroot, but I didn't find fdo backend there at all.

If there is any docs or articles about hardware acceleration in wpe, poring wpe to new platforms, etc  - would highly appreciate some directions.

**Comment by aperezdc** [comment]
Hardware acceleration is always enabled for WPE WebKit, and it will not run without a GPU. If Cog is displaying web content for you, then things are working as expected. You don't need to patch Cairo to get acceleration :wink: 

The `ENABLE_ACCELERATED_2D_CANVAS` option only applies to `<canvas>` elements, and the default build settings leave it disabled because in some cases it is actually worse to have it enabled (in some cases it helps a bit, though!).

Note that currently rasterization (painting) in WPE WebKit is still done in software using Cairo: the page is divided in square tiles, each tile painted, uploaded to the GPU, and then GPU is used for compositing the tiles and applying transformations and animation to them. In particular, you should be able to notice that pages using CSS Animations and CSS Transforms animate smootly—in many cases at a constant 60 FPS—because the GPU is doing most of the work for those. For a quick test you can try the [poster circle animation](https://people.igalia.com/aperez/poster-circle.html).

Finally, please note that a web engine like WPE WebKit does many, many more things than “pure” OpenGL programs like glmark.

**Comment by aperezdc** [comment]
Regarding WebGL, it is expected to work with WPEBackend-fdo, but some pages which use WebGL may require features which the Lima driver (or the Mali GPU) does not support.

Simple examples like those from [the MDN WebGL tutorial](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Creating_3D_objects_using_WebGL) should work with most drivers—unless there is a bug in the driver, of course.

**Comment by mcatanzaro** [comment]
Can this be closed?

**Comment by aperezdc** [comment]
> Can this be closed?

Yes, I think so.

@dossalab Please feel free to reopen and comment if you have any other doubts or questions :smile_cat:
